CREATE TABLE vendors(
id INT NOT NULL UNIQUE PRIMARY KEY AUTO_INCREMENT,
vendor VARCHAR(255),
regdate TIMESTAMP
);

CREATE TABLE users(
id INT NOT NULL UNIQUE PRIMARY KEY AUTO_INCREMENT,
email VARCHAR(255),
regdate TIMESTAMP,
active BOOLEAN,
token VARCHAR(255)
);

CREATE TABLE passwords(
id INT NOT NULL UNIQUE PRIMARY KEY AUTO_INCREMENT,
uid INT,
secpasswd VARCHAR(255),
regdate TIMESTAMP
);

CREATE TABLE apikeys(
id INT NOT NULL UNIQUE PRIMARY KEY AUTO_INCREMENT  ,
uid INT ,
securekey VARCHAR(255),
regdate TIMESTAMP,
vendorid INT
);

CREATE TABLE searchterm(
id INT NOT NULL UNIQUE PRIMARY KEY AUTO_INCREMENT,
uid INT,
term VARCHAR(255),
regdate TIMESTAMP,
cnt INT
);

CREATE TABLE keywords(
id INT NOT NULL UNIQUE PRIMARY KEY AUTO_INCREMENT,
uid INT,
termid INT,
keyone VARCHAR(255),
keytwo VARCHAR(255),
keythree VARCHAR(255),
regdate TIMESTAMP,
cnt INT
);
